// Code generated by mockgen. DO NOT EDIT.
// Source: limits.go

package limits

import (
	"context"
	"sync"
)

type MockTotals struct {
	mu    sync.Mutex
	calls []string
	Spent int64
	Limit int64
	Err   error
}

func (m *MockTotals) SpentToday(ctx context.Context, account string) (int64, int64, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.calls = append(m.calls, account)
	return m.Spent, m.Limit, m.Err
}

func (m *MockTotals) Calls() []string {
	m.mu.Lock()
	defer m.mu.Unlock()
	return append([]string(nil), m.calls...)
}
